$base = <<BASE
#Packages
sudo yum install -y jq go git unzip docker postgresql
#Docker
sudo groupadd docker
sudo usermod -aG docker vagrant
sudo systemctl enable docker.service
sudo service docker start
BASE


$go = <<GO
echo "Building go app..."
cd /vagrant/go-workspace/src/github.com/lanceplarsen/go-vault-demo
export GOPATH=/vagrant/go-workspace
export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
go get
go build
echo "Building go docker..."
docker build -t go .
GO

$postgres = <<POSTGRES
sleep 10
psql -h localhost -U postgres -d postgres -c 'DROP TABLE IF EXISTS "orders"'
psql -h localhost -U postgres -d postgres -a -f /vagrant/go-workspace/src/github.com/lanceplarsen/go-vault-demo/scripts/postgres.sql
POSTGRES

$vault_install = <<VAULT_INSTALL
#Get Vault
VAULT=0.10.3
VAULT_ZIP=/vagrant/bin/vault_${VAULT}_linux_amd64.zip
if [ ! -f $VAULT_ZIP ]; then
  mkdir -p /vagrant/bin
  wget https://releases.hashicorp.com/vault/${VAULT}/vault_${VAULT}_linux_amd64.zip --quiet -O $VAULT_ZIP
fi
cd /tmp
unzip -q $VAULT_ZIP >/dev/null
sudo chmod +x vault
sudo mv vault /usr/bin
sudo chmod 0755 /usr/bin/vault
sudo chown root:root /usr/bin/vault
#Policy permissions
chmod +x /vagrant/go-workspace/src/github.com/lanceplarsen/go-vault-demo/scripts/vault.sh
VAULT_INSTALL

$vault_policy = <<VAULT_POLICY
#Create Policy
export VAULT_ADDR=http://127.0.0.1:8200
vault login root
/vagrant/go-workspace/src/github.com/lanceplarsen/go-vault-demo/scripts/vault.sh
VAULT_POLICY

Vagrant.configure("2") do |config|
  config.vm.synced_folder "../../", "/vagrant/go-workspace/src/github.com/lanceplarsen/go-vault-demo"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "1"]
  end
  config.vm.define "demo" do |demo|
    demo.vm.box = "bento/centos-7.4"
    demo.vm.hostname = "demo.example.com"
    demo.vm.network :private_network, type: "dhcp"
    demo.vm.network :private_network, ip: "192.168.50.151"
    demo.vm.network :forwarded_port, guest: 8200, host: 8200
    demo.vm.network :forwarded_port, guest: 3000, host: 3000
    demo.vm.network :forwarded_port, guest: 5432, host: 5432
    demo.vm.provision "shell", inline: $base
    demo.vm.provision "shell", inline: $go
    demo.vm.provision "shell", inline: $vault_install
    demo.vm.provision "docker" do |d|
      d.run "postgres",
        args: "--net=host -d"
      d.run "vault",
        image: "vault:0.10.4",
        args: "--net=host --cap-add=IPC_LOCK -e 'VAULT_DEV_ROOT_TOKEN_ID=root' -e 'VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200' -d"
      d.run "go",
        args: "--net=host -v /vagrant/go-workspace/src/github.com/lanceplarsen/go-vault-demo/config.toml:/app/config.toml -e 'VAULT_TOKEN=root' -d"
    end
    demo.vm.provision "shell", inline: "sudo docker restart postgres vault go", run: "always"
    demo.vm.provision "shell", inline: $postgres, run: "always"
    demo.vm.provision "shell", inline: $vault_policy, run: "always"
  end
end
